# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64cdf9589ce562ee10925fbc50d37be3c2089ee70adaca919992f0b3c4ea049218be865fb5469e7bc3f4e9209ad2a877362f72b15ffcf409779e67fa84a479f8

test:
  secret_key_base: d07f179c390e3547461091a7ad0c28d933dc629beba8e29b3f78aaad213fcdede2a13454061f70cf451a3e3dea16ed1c88c3d134b2bf5a29cf4e3d6560072f70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
